E_Learning/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('course/', include('course.urls')),
    path('search/',include('search.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import IndexView, LoginView,SignupPage, UserProfileDetailView,LogoutPage,EditProfileView,EditProfileData

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupPage.as_view(), name='signup'),
    path('profile/<int:pk>/', UserProfileDetailView.as_view(), name='userprofile-detail'),
    path('logout/', LogoutPage.as_view(),name='logout'),
    path('edit_profile/', EditProfileView.as_view(), name='edit-profile'),
    path('edit_profile_data/', EditProfileData.as_view(), name='edit_profile_data'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.CharField(max_length=122,blank=True)
    email = models.EmailField(max_length=122,blank=True)
    phone = models.CharField(max_length=13,blank=True)
    password = models.CharField(max_length=122,blank=True)
    bio = models.TextField(blank=True)
    picture = models.ImageField(upload_to='profile_pics', blank=True)
    skill_set = models.CharField(max_length=200,blank=True)
    learning_interests = models.CharField(max_length=200,blank=True)
    completed_courses = models.CharField(max_length=200,blank=True)
    certifications = models.CharField(max_length=200,blank=True)
    
    def __str__(self):
        return self.user

home/views.py
from django.views import View
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from .models import UserProfile
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView as AuthLoginView
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.urls import reverse

class IndexView(View):
    def get(self, request):
        return render(request,'home.html')
    

class LoginView(AuthLoginView):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        uname = request.POST.get('username')
        passw = request.POST.get('password')

        user = authenticate(request, username=uname, password=passw)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(self.request, 'Invalid username or password ')
            return render(request, 'login.html')
   

class SignupPage(View):
    def get(self, request):
        return render(request, 'signup.html')

    def post(self, request):
        uname = request.POST.get('username')
        email = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')

        if pass1 != pass2:
            messages.error(self.request, 'Your password and confirm password are not the same!')
            return render(request, 'signup.html')
        
        elif UserProfile.objects.filter(user=uname).exists():
            messages.error(self.request, 'Username is already taken!')
            return render(request, 'signup.html') 
        
        else:
            my_auth_user = User.objects.create_user(uname,email,pass1)
            my_auth_user.save()
            my_user = UserProfile(user=uname, email=email, password=pass1)
            my_user.save()
            messages.success(self.request, 'You have successfully registered! Please login to continue.')
            return redirect('login')


class UserProfileDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'userprofile_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_profile = UserProfile.objects.get(user=self.request.user)
        context['user_profile'] = user_profile
        return context
      
class LogoutPage(View):
    def get(self, request):
        logout(request)
        return redirect('home')
    
class EditProfileView(View):
    def post(self, request):
       pic = request.FILES.get('picture')
       user_profile = UserProfile.objects.get(user=request.user)
       user_profile.picture = pic
       user_profile.save()
       return redirect(reverse('userprofile-detail', kwargs={'pk': user_profile.pk}))
    
class EditProfileData(LoginRequiredMixin, TemplateView):
    template_name = 'userprofile_update.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_profile = UserProfile.objects.get(user=self.request.user)
        context['user_profile'] = user_profile
        return context

    def post(self, request):
        phone = request.POST.get('phone')
        skill = request.POST.get('skill')
        Learning_interests = request.POST.get('Learning_interests')
        courses = request.POST.get('courses')
        bio = request.POST.get('bio')
        user_profile = UserProfile.objects.get(user=request.user)
        user_profile.phone = phone
        user_profile.skill_set=skill
        user_profile.learning_interests = Learning_interests
        user_profile.completed_courses = courses
        user_profile.bio = bio
        user_profile.save()
        return redirect(reverse('userprofile-detail', kwargs={'pk': user_profile.pk}))

templates/course_data.html
{% extends 'index.html' %} 
{% block title %} Course-Data {% endblock title %}

{% block body %}
<div class="container pt-5">
  <div class="row">
    <div class="col-md-6">
      <h3>{{ course_data.count }} Course Data</h3>
    </div>
    <div class="col-md-6 text-right">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#upload-modal">
        Upload File
      </button>
    </div>
  </div>
  <hr>
  {% if course_data %}
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>File</th>
          <th>Created At</th>
          <th>Instructor</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for data in course_data %}
          <tr>
            <td>{{ data.title }}</td>
            <td>{{ data.description }}</td>
            <td><a href="{{ data.file.url }}" target="_blank">{{ data.file.name }}</a></td>
            <td>{{ data.created_at }}</td>
            <td>{{ data.instructor }}</td>
            <td>
              <form method="post" action="{% url 'delete_course_data' data.pk %}" >
                {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No course data available.</p>
  {% endif %}
</div>

<!-- Upload Modal -->
<div class="modal fade" id="upload-modal" tabindex="-1" aria-labelledby="upload-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <form    method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="upload-modal-label">Upload Course Data</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{ form.as_p }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Upload</button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.1/dist/esm/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

{% endblock body %}

templates/create_course.html
{% extends 'index.html' %} {% block title %} Create-Course {% endblock title %}
{% block body %}

<div class="container pt-5">
  {% if user_courses %}
  <div class="row">
    <div class="col-md-12">
      <h2>Your Courses</h2>
    </div>
  </div>
  <div class="row">
    {% for course in user_courses %}
    <div class="col-md-4">
      <div class="card mb-4" style="height: 370px">
        <img
          src="{{ course.course_image.url }}"
          class="card-img-top"
          alt="{{ course.name }} Image"
          style="object-fit: cover; height: 200px; width: 100%"
        />
        <div class="card-body" style="overflow: auto">
          <h5 class="card-title">{{ course.name }}</h5>
          <p class="card-text">{{ course.description }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <a href= "{% url 'Course-Data' course.id %}" class="btn btn-primary">View Course</a>
            <div class="dropdown ml-auto">
              <button
                class="btn btn-secondary dropdown-toggle"
                type="button"
                id="course-actions-{{ course.id }}"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                ...
              </button>
              <ul
                class="dropdown-menu"
                aria-labelledby="course-actions-{{ course.id }}"
              >
                {% if course.enrollment_key %}
                <li>
                  <a
                    class="dropdown-item"
                    href="#"
                    data-bs-toggle="modal"
                    data-bs-target="#enrollment-key-modal-{{ course.id }}"
                    >{{ 'Enrollment Key' }}</a
                  >
                </li>
                {% endif %}
                <li>
                  <button
                    class="dropdown-item"
                    type="button"
                    data-bs-toggle="modal"
                    data-bs-target="#confirm-delete-modal-{{ course.id }}"
                  >
                    Delete Course
                  </button>
                </li>
              </ul>
            </div>
          </div>
          <!-- Enrollment Key Modal -->
          {% if course.enrollment_key %}
          <div
            class="modal fade"
            id="enrollment-key-modal-{{ course.id }}"
            tabindex="-1"
            aria-labelledby="enrollment-key-modal-label"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="enrollment-key-modal-label">
                    {{ 'Enrollment Key' }}
                  </h5>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <p>{{ course.enrollment_key }}</p>
                </div>
              </div>
            </div>
          </div>
          {% endif %}
          <!-- Confirm Delete Modal -->
          <div
            class="modal fade"
            id="confirm-delete-modal-{{ course.id }}"
            tabindex="-1"
            aria-labelledby="confirm-delete-modal-label"
            aria-hidden="true"
          >
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="confirm-delete-modal-label">
                    Delete Course
                  </h5>
                  <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  ></button>
                </div>
                <div class="modal-body">
                  <p>Are you sure you want to delete "{{ course.name}}"?</p>
                </div>
                <div class="modal-footer">
                  <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal"
                  >
                    Cancel
                  </button>
                  <form
                    action="{% url 'delete_course' course.id %}"
                    method="POST"
                  >
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="row">
    <div class="col-md-12">
      {% else %}
      <div class="alert alert-info">
        You do not have any courses yet. Please create a course to get started.
      </div>
      {% endif %}
      <button
        type="button"
        class="btn btn-primary mt-3"
        data-bs-toggle="modal"
        data-bs-target="#create-course-modal"
      >
        Create New Course
      </button>
    </div>
  </div>
</div>

<!-- Create Course Modal -->
<div
  class="modal fade"
  id="create-course-modal"
  tabindex="-1"
  aria-labelledby="create-course-modal-label"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="create-course-modal-label">
          Create a Course
        </h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{ form.as_p }}
          <div class="form-check mb-3">
            <input
              class="form-check-input"
              type="checkbox"
              value="on"
              name="generate_enrollment_key"
              id="generate-enrollment-key"
            />
            <label class="form-check-label" for="generate-enrollment-key">
              Generate enrollment key
            </label>
          </div>
          <button type="submit" class="btn btn-primary">Create Course</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/enroll_course_detail.html
{% extends 'index.html' %}

{% block title %}Course Detail{% endblock title %}

{% block head %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.1/dist/esm/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
{% endblock head %}

{% block body %}
<div class="container pt-4">
    <h1>Course Detail</h1>
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ course.name }}</h5>
            <p class="card-text">{{ course.description }}</p>
            <p class="card-text">Instructor: {{ course.instructor }}</p>
            <p class="card-text">Start Date: {{ course.start_date }}</p>
            <p class="card-text">End Date: {{ course.end_date }}</p>
            <!-- Add more course details as needed -->
        </div>
    </div>
    <div class="row">
        <hr>
        {% if course_data %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>File</th>
                        <th>Created At</th>
                        <th>Instructor</th>
                    </tr>
                </thead>
                <tbody>
                    {% for data in course_data %}
                        <tr>
                            <td>{{ data.title }}</td>
                            <td>{{ data.description }}</td>
                            <td><a href="{{ data.file.url }}" target="_blank">{{ data.file.name }}</a></td>
                            <td>{{ data.created_at }}</td>
                            <td>{{ data.instructor }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No course data available.</p>
        {% endif %}
    </div>
</div>
{% endblock body%}

templates/enrolled_courses.html
{% extends 'index.html' %} {% block title %} Create-Course {% endblock title %}
{% block body %}

<div class="container pt-5">
  <h1>Enrolled Courses</h1>
  {% if enrollments %}
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for enrollment in enrollments %}
    <div class="col-md-4">
      <div class="card mb-4" style="height: 390px">
        
          <img
            src="{{ enrollment.course.course_image.url }}"
            class="card-img-top"
            alt="{{ course.name }} Image"
            style="object-fit: cover; height: 200px; width: 100%"
          />
           <div class="card-body" style="overflow: auto">
          <h5 class="card-title">{{ enrollment.course.name }}</h5>
          <p class="card-text">{{ enrollment.course.description }}</p>
          <p class="card-text">
            Instructor: {{ enrollment.course.instructor }}
          </p>
          <a href="{% url 'course-data-detail' enrollment.course.id %}" class="btn btn-primary">View Course</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>No enrolled courses found.</p>
  {% endif %}
</div>
{% endblock body %}

templates/home.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    {{ block.super }}

    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
    
{% endblock %}

{% block title %}
Home
{% endblock title %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="text-container">
                <h1 class="display-4 mt-4">Welcome to our E-Learning Platform!</h1>
                <p class="lead">We provide high-quality courses for learners around the world.</p>
                <hr >
                <p class="op1"> Start your e-learning journey with us and learn new skills. Our platform offers a wide range of courses that cover various topics and industries. Join us and gain access to expert instructors, interactive content, and practical exercises that will help you achieve your goals.</p>
                {% if user.is_authenticated %}
                    <a href="{% url 'course-create'%}" role="button" class="btn btn-primary">Get Started</a>
                {% else %}
                    <a href="/signup" role="button" class="btn btn-primary">Get Started</a>
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'home_image1.jpg' %}" class="d-block w-100" alt="Image 1" width="500" height="500">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'home_image2.jpg' %}" class="d-block w-100" alt="Image 2" width="600" height="500">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'home_image3.jpg' %}" class="d-block w-100" alt="Image 3" width="500" height="500">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'home_image4.jpg' %}" class="d-block w-100" alt="Image 4" width="600" height="500">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $('.carousel').carousel({
        interval: 0.000000001 // change the slide interval as per your requirement
    })
</script>
{% endblock body %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} {% endblock title %} | E-learning</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">E-Learning Platform</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Courses
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'search-course' %}">Search Courses</a></li>
                <li><a class="dropdown-item" href="{% url 'enrolled-courses' %}">Enrolled Courses</a></li>
                
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'course-create' %}">Create Course</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userprofile-detail' pk=user.id %}"> <i class="fas fa-user-circle fa-2x"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/signup">Sign Up</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>  

    <div class="container mt-5">
      {% block body %} {% endblock body %}
    </div>
    <footer class="footer bg-dark text-light mt-5">
      <div class="container text-center">
          <div class="row pt-5">
              <div class="col-md-4">
                <h4>About Us</h4>
                <p>Welcome to our E-Learning Platform! We provide a comprehensive online learning experience for learners of all backgrounds. Our platform offers a diverse selection of courses in various fields, allowing you to expand your knowledge and acquire new skills from the comfort of your home.</p>
            </div>
            <div class="col-md-4">
                <h4>Contact Information</h4>
                <p><i class="fas fa-map-marker-alt"></i> IIT, Roorkee, India</p>
                <p><i class="fas fa-phone"></i> +918502048440</p>
                <p><i class="fas fa-envelope"></i> rohitjingar264@gmail.com</p>
            </div>
            <div class="col-md-4">
                <h4>Follow Us</h4>
                <div class="social-icons">
                    <a href="https://www.facebook.com/rohitkumar.solanki.5074?mibextid=ZbWKwL"><i class="fab fa-facebook-f"></i></a>
                    <a href="https://twitter.com/jingar_rohit?t=nbCYYGaex6bzRFDV5zgM8w&s=08"><i class="fab fa-twitter"></i></a>
                    <a href="https://instagram.com/rohit__jingar45?igshid=OTk0YzhjMDVlZA=="><i class="fab fa-instagram"></i></a>
                    <a href="https://www.linkedin.com/in/rohit-kumar-jingar-9271a9222"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
        <hr>
        <p>© 2023 E-Learning Platform. All rights reserved.</p>
    </div>
</footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/login.html
{% extends 'index.html' %}

{% block title %}
Login
{% endblock title %}

{% block body %}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 mt-5">
      <h2>Login</h2>
      {% if messages %}
      {% for message in messages %}
      {% if message.tags == 'error' %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
      {% endfor %}
      {% endif %}
      <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        
        <div class="mb-3">
          <label for="username" class="form-label">Username</label>
          <input required type="text" class="form-control" id="username" name="username">
         
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          <input required type="password" class="form-control" id="password" name="password">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
    </div>
  </div>
</div>
{% endblock body %}

templates/userprofile_detail.html
{% extends 'index.html' %}

{% block title %}
User Profile
{% endblock title %}

{% load static %}
{% block body %}
<div class="container pt-5">
  <div class="row">
    <div class="col-md-4 mb-4">
        <div class="card shadow-sm">
          <div class="card-body text-center">
            {% if user_profile.picture %}
              <img src="{{ user_profile.picture.url }}" alt="{{ user_profile.user }}" class="rounded-circle mb-3" style="width: 200px; height: 200px; object-fit: cover;">
            {% else %}
              <a class="nav-link"><i class="fas fa-user-circle fa-5x"></i></a>
            {% endif %}
            
            <form action="{% url 'edit-profile' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="form-group mt-6">
                <label for="id_picture">Profile Picture:</label>
                <input type="file" name="picture" class="form-control-file ml-auto " id="id_picture">
              </div>
              <button  type="submit" class="btn btn-primary mt-2">Save</button>
            </form>
          </div>
        </div>
      </div>
    <div class="col-md-8 ">
      <div class="card border border-dark mb-3">
        <div class="card-header">
          <h4 class="card-title">{{ user_profile.user }}</h4>
        </div>
        <div class="card-body">
          <p class="card-text"><strong>Email:</strong> {{ user_profile.email }}</p>
          <p class="card-text"><strong>Phone:</strong> {{ user_profile.phone }}</p>
          <p class="card-text"><strong>Skill set:</strong> {{ user_profile.skill_set }}</p>
          <p class="card-text"><strong>Learning interests:</strong> {{ user_profile.learning_interests }}</p>
          <p class="card-text"><strong>Completed courses:</strong> {{ user_profile.completed_courses }}</p>
          <p class="card-text"><strong>Bio:</strong> {{ user_profile.bio }}</p>
        </div>
      </div>
      <a href="{% url 'edit_profile_data' %}" class="btn btn-primary mt-2 ">Edit Profile</a>
    </div>

  </div>
</div>
{% endblock body %}